"""Trust Report models — the design-criterion winner.

A weekly, one-page, plain-English document addressed to a non-technical
director. Generated by Gemini from accumulated verdicts and Phoenix monitor
data, with a fixed template so it never rambles. No metric appears without a
sentence of meaning.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class TopicStat(BaseModel):
    """Per-topic rollup used to compute riskiest/safest and corpus gaps."""

    topic: str
    answered: int = Field(default=0, ge=0)
    cleared: int = Field(default=0, ge=0)
    corrected: int = Field(default=0, ge=0)
    held: int = Field(default=0, ge=0)

    @property
    def quarantine_rate(self) -> float:
        return (self.held / self.answered) if self.answered else 0.0


class TrustReport(BaseModel):
    """The rendered weekly report. Each section maps to a fixed template slot."""

    org_name: str = Field(default="Riverside Community Legal Aid")
    week_of: str = Field(..., description="ISO date of the Monday this report covers.")
    generated_at: str

    total_answered: int = Field(default=0, ge=0)
    cleared: int = Field(default=0, ge=0)
    corrected: int = Field(default=0, ge=0)
    held: int = Field(default=0, ge=0, description="Quarantined and still pending the team's review.")
    reviewed: int = Field(default=0, ge=0, description="Quarantined and since acted on by a director.")

    headline: str = Field(
        ...,
        min_length=1,
        description="The opening sentence, e.g. 'This week, your assistant answered 412 questions.'",
    )
    what_was_caught: list[str] = Field(
        default_factory=list,
        description="Plain-English bullets describing the concrete catches, with sources.",
    )
    trend: str = Field(
        ..., description="Plain-English trend, incl. stale-corpus nudges from monitor data."
    )
    riskiest_topic: str = Field(default="")
    safest_topic: str = Field(default="")
    corpus_gaps: list[str] = Field(
        default_factory=list,
        description="Topics the corpus does not cover well — a feature, not a bug (corpus-gap analysis).",
    )
    topic_stats: list[TopicStat] = Field(default_factory=list)
    disclaimer: str = Field(
        default=(
            "Sentinel reduces risk; it does not eliminate it. Quarantine thresholds are your "
            "clinic's policy, and human review remains mandatory for high-stakes answers."
        ),
        description="Ethical guardrail — stated on every report.",
    )
